language: node_js

node_js:
  - 10.15.3

cache:
  directories:
    - ./node_modules

before_script:
  - npm install --path path-to-your-frontend-folder

script:
  - npm run test --prefix path-to-your-frontend-folder
