language: node_js
notifications:
email: true
node_js: 12.18.1
jobs:
  include:
    - stage: test
      script:
        - npm run build
        - npm run lint
        - npm run test
    - stage: deploy
      if: branch = master
      script: npm run deploy
